import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import localFont from "next/font/local";
import { CookieConsentBanner } from "@/components/cookies/cookie-consent-banner";
import { CartDrawer } from "@/components/cart/cart-drawer";
import { CartProvider } from "@/components/cart/cart-provider";

import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const satoshi = localFont({
  src: "../../public/font/Satoshi-Variable.ttf",
  variable: "--font-satoshi",
  weight: "400 500 600 700 800",
  style: "normal",
  display: "swap",
});
const clashDisplay = localFont({
  src: "../../public/font/ClashDisplay-Variable.ttf",
  variable: "--font-clashDisplay",
  weight: "400 500 600 700 800",
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${satoshi.variable} ${clashDisplay.variable} font-satoshi h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          {children}
          <CartDrawer />
        </CartProvider>
        {/* <CookieConsentBanner /> */}
      </body>
    </html>
  );
}
